### ISSUE TITLE
Static library target

### ISSUE THREAD

**Issue by b-smets** [reidmain/FDKeychain#4]
Hi,

The following commit removed the static library target from the build targets:
https://github.com/reidmain/FDKeychain/commit/d00106de3e3a5debf62ed530218419c08c40a30c

Without the static library target, FDKeychain can no longer be used in other static library projects. For the library we are building, we try to minimize third party frameworks as they impose extra work on the user of the library.

Is it possible to add this target once more?

**Comment by reidmain** [comment]
Sorry but going forward I am only going to be supporting iOS 8+ which means there is no reason to not use FDKeychain as a framework. If your users need to use the static library target you could point them to the commit just before d00106d and have them link against that. There are no plans to heavily modify FDKeychain at this point.

However FDKeychain was setup to be extremely easy to integrate because you can simply just copy FDKeychain.h and FDKeychain.m into your project. It even uses modules and the `@import` syntax so the users of your library shouldn't even need to add a dependency on the Security framework (and at this point in time they really should be using modules).

Were your instructions before to just add FDKeychain's static library as a target dependency after they added your library?
