### ISSUE TITLE
iOS 7+ Compatible ?

### ISSUE THREAD

**Issue by omarojo** [reidmain/FDKeychain#6]
I just wanted to know if this library can be used in iOS 7 devices, using Cocoapods as the method to install it.

**Comment by reidmain** [comment]
Technically it is iOS 7 compatible. It it just no longer supported. https://github.com/reidmain/FDKeychain/commit/d00106de3e3a5debf62ed530218419c08c40a30c switched over to only supporting iOS 8 and up because I only plan on supporting the two latest iOS version and I wanted to make a dynamic framework.

However the latest version published to Cocoapods is 1.2.2 which still supports iOS 7 https://github.com/CocoaPods/Specs/blob/master/Specs/FDKeychain/1.2.2/FDKeychain.podspec.json so you should be fine if you pin yourself to 1.2.2
